version: '3.8'

services:
  db:
    image: postgres:15
    container_name: DB_postgres
    environment:
      POSTGRES_USER: user_got_mad
      POSTGRES_PASSWORD: User&M@4
      POSTGRES_DB: postgresdb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

